
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGNMENT PIPE QUOTED_STRING WORDassignment : WORD ASSIGNMENT WORDcommand : WORD\n                | command WORD\n                | command QUOTED_STRING command_line : command\n                    | command PIPE command_line '
    
_lr_action_items = {'ASSIGNMENT':([2,],[3,]),'$end':([1,4,],[0,-1,]),'WORD':([0,3,],[2,4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assignment","S'",1,None,None,None),
  ('assignment -> WORD ASSIGNMENT WORD','assignment',3,'p_assignment','Lexer.py',35),
  ('command -> WORD','command',1,'p_command','Lexer.py',38),
  ('command -> command WORD','command',2,'p_command','Lexer.py',39),
  ('command -> command QUOTED_STRING','command',2,'p_command','Lexer.py',40),
  ('command_line -> command','command_line',1,'p_command_line','Lexer.py',45),
  ('command_line -> command PIPE command_line','command_line',3,'p_command_line','Lexer.py',46),
]
